### ISSUE TITLE
Calling `compile(..)` leads to "TypeError: UTIL.inherits is not a function"

### ISSUE THREAD

**Issue by jsdw** [paritytech/js-revive#1]
Hello!

Having a go playing with smart contracts and making a UI, I ran into the titled error. My code:

```ts
import { compile } from '@parity/revive'

const CONTRACT_NAME = "Message"
const CONTRACT = `
  // SPDX-License-Identifier: GPL-3.0
  pragma solidity >=0.7.0 <0.9.0;

  contract Message {

      address payable public owner;
      string public message;

      event MessageChanged(string message);

      constructor() {
          owner = payable(msg.sender);
      }

      function setMessage(string calldata m) external payable {
          require(msg.value >= 1 ether, "1 ETH required");
          message = m;
          emit MessageChanged(m);
      }

      function withdraw(uint amount) external {
          require(msg.sender == owner, "Only the contract owner can call this");
          (bool success, ) = msg.sender.call{ value: amount }("");
          require(success, "Transfer failed");
      }
  }
`

compile({
      [CONTRACT_NAME]: {
        content: CONTRACT,
      },
})
```

Running this leads to the titled error:

<img width="727" alt="Screenshot 2024-11-14 at 16 53 35" src="https://github.com/user-attachments/assets/161cc3ef-0965-4cda-9df7-adb5fbea04c1">

Commenting out the `compile` line makes the error go away.

This could well be something totally unrelated since I'm new to smart contracts, but I wanted to raise it just incase :)

My dependencies (Using SolidJS's default TS template with Vite to play around here):

```
  "devDependencies": {
    "solid-devtools": "^0.29.2",
    "typescript": "^5.3.3",
    "vite": "^5.0.11",
    "vite-plugin-solid": "^2.8.2"
  },
  "dependencies": {
    "@parity/revive": "^0.0.5",
    "ethers": "^6.13.4",
    "solid-js": "^1.8.11"
  }
```

**Comment by jsdw** [comment]
Ah perhaps I can answer my own bug; is this not supposed to work client side?

I see in the tutorial (https://contracts.polkadot.io/getting-started-with-ethers.js): "Using Node.js, Deno, or Bun, you can compile your contract to Polkavm bytecode using the @parity/revive package." which hints that this step isn't browser friendly :)

**Comment by pgherveou** [comment]
Yes sorry for now it's not, it will once we ditch the backend and start using the wasm compiler
